; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:cezerio_dev_esp32c6]
platform = espressif32
board = cezerio_dev_esp32c6
framework = espidf

upload_port = COM19
upload_speed = 921600  

monitor_port = COM19
monitor_speed = 115200
